### ISSUE TITLE
Display important Details

### ISSUE THREAD

**Issue by annamarika** [annamarika/capstone-project#1]
# Value Proposition

**As a** friend who likes to share
**I need** to display the details of my product
**to be able to** define my product and monitor my inventory

# Description

![01_MVP](https://user-images.githubusercontent.com/88536158/167394379-c7e0c04f-fe12-47d6-a484-f3accaafcb61.jpg)

# Acceptance Criteria

- [x] The details are displayed
- [x] The email is displayed
- [x] The Image is displayed

# Tasks

- [x] Create a new branch "display-product"
- [x] Create the data structure to hold the product details
- [x] Create a new component to render the data in a `<p>` and `<img>` tag
- [x] The component receives product details via props
- [x] Add to Storybook
- [x] Apply basic styling
- [x] Add test to check if data is rendered

# Complexity
M

**Comment by doemser** [comment]
Looks good!
You could try to specify your task with the data structure even further:
Which kind of data-structure makes sense?
Where do you store it?
