### ISSUE TITLE
Add Bookmark Page

### ISSUE THREAD

**Issue by annamarika** [annamarika/capstone-project#23]
# Value Proposition

**As a** User
**I need** to mark my favourites
**to be able to** look them up later

# Description

<img src="https://user-images.githubusercontent.com/88536158/171176786-1ad12be6-af17-4781-944a-50fb2a8d27c5.png" width="400" />

# Acceptance Criteria

- [ ] on every product is a heart icon
- [ ] on click the heart icon changes color and gets stored and the bookmark page
- [ ] on a second click the heart icon gets deactivated again

# Tasks

(for developers team)

- [ ]  Add a new branch "Add-bookmark"
- [ ] create a bookmark component
- [ ] add the bookmark component to the product component
- [ ] create a bookmark page 
- [ ] display bookmarked entries on bookmark page
- [ ] filter all products if they bookmarked or not

# Complexity
L
